apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufac
  namespace: manufac-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manufac
  interval: 1m
  chart:
   spec:
    chart: platforms/r3-corda-ent/charts/node
    sourceRef:
      kind: GitRepository
      name: flux-vara
      namespace: flux-vara
  values:
    nodeName: manufac
    metadata:
      namespace: manufac-ent
      labels:
    image:
      initContainerName: blockchainfulcrumacr.azurecr.io/alpine-utils:1.0
      nodeContainerName: blockchainfulcrumacr.azurecr.io/corda/enterprise-node:4.7
      imagepullsecret: regcred
      pullPolicy: IfNotPresent
    acceptLicence: true
    storage:
      name: manufac-aws-storageclass
    replicas: 1
    networkServices:
      doormanURL: https://idman.sai29.dev.aws.blockchaincloudpoc-develop.com
      networkMapURL: https://networkmap.sai29.dev.aws.blockchaincloudpoc-develop.com
      idmanDomain: "idman.sai29.dev.aws.blockchaincloudpoc-develop.com"
      networkMapDomain: "networkmap.sai29.dev.aws.blockchaincloudpoc-develop.com"
      idmanName: "idman"
      networkmapName: "networkmap"
    firewall:
      enabled: True
    vault:
      address: http://a39f5128b6763403fbe629cbb6978dc2-1224147318.eu-west-1.elb.amazonaws.com:20001
      role: vault-role
      authpath: cordaentmanufac
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/manufac/manufac
      nodePath: manufac
      retries: 30
      retryInterval: 30
    cordapps:
      getcordapps: true
      jars:
        - url: https://maven.pkg.github.com/hyperledger/bevel/com.supplychain.bcc.cordapp-supply-chain/4.7/cordapp-supply-chain-4.7.jar
        - url: https://maven.pkg.github.com/hyperledger/bevel/com.supplychain.bcc.cordapp-contracts-states/4.7/cordapp-contracts-states-4.7.jar
        
    nodeConf:
      ambassador:
        external_url_suffix: sai29.dev.aws.blockchaincloudpoc-develop.com
        p2pPort: 15042
        p2pAddress: float.manufac.sai29.dev.aws.blockchaincloudpoc-develop.com:15020
      legalName: "O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH"
      emailAddress: "dev-node@bevel.com"
      crlCheckSoftFail: true
      tlsCertCrlDistPoint: ""
      tlsCertCrlIssuer: "CN=Corda TLS CRL Authority,OU=Corda UAT,O=R3 HoldCo LLC,L=New York,C=US"
      devMode: false
      volume:
        baseDir: /opt/corda/base
      jarPath: bin
      configPath: etc
      cordaJar:
        memorySize: 1524
        unit: M
      pod:
        resources:
          limits: 1524M
          requests: 1524M
    service:
      p2pPort: 10002
      p2pAddress: manufac.manufac-ent
      messagingServerPort: 10002
      ssh:
        enabled: true
        sshdPort: 2222
      rpc:
        port: 30000
        adminPort: 30009
        users:
        - name: manufac
          password: manufacP
          permissions: ALL
    dataSourceProperties:
      dataSource:
        user: manufac-db-user
        password: manufac-db-password
        url: "jdbc:h2:tcp://manufacdb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        dbUrl: "manufacdb"
        dbPort: 9101
      monitoring:
        enabled: true
        port: 8090
      allowDevCorDapps:
        enabled: true
      retries: 20
      retryInterval: 15
    sleepTimeAfterError: 120
    sleepTime: 0
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
