##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.nodeName }}
{{ if $.Values.ambassador }}
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ .Values.nodeName }}-listener
  namespace: {{ .Values.metadata.namespace }}
spec:
  port: {{ .Values.ambassador.port }}
  protocol: TCP
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF
---
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: {{ .Values.nodeName }}-mapping
  namespace: {{ .Values.metadata.namespace }}
spec:
  port: {{ .Values.ambassador.port }}
  service: {{ .Values.nodeName }}.{{ .Values.metadata.namespace }}:{{ .Values.service.port }}
  tls: {{ .Values.nodeName }}-mapping-tlscontext
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: {{ .Values.nodeName }}-mapping-tlscontext
  namespace: {{ .Values.metadata.namespace }}
spec:
  hosts:
  - {{ .Values.nodeName }}.{{ .Values.ambassador.external_url_suffix }}
  secret: {{ .Values.nodeName }}-ambassador-certs.{{ .Values.metadata.namespace }}
  secret_namespacing: true
  min_tls_version: v1.2
{{ end }}
