apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notary-1
  namespace: supplychyn-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: notary-1
  interval: 1m
  chart:
   spec:
    chart: platforms/r3-corda-ent/charts/notary
    sourceRef:
      kind: GitRepository
      name: flux-vara
      namespace: flux-vara
  values:
    nodeName: notary-1
    metadata:
      namespace: supplychyn-ent
    image:
      initContainerName: blockchainfulcrumacr.azurecr.io/alpine-utils:1.0
      nodeContainerName: blockchainfulcrumacr.azurecr.io/corda/enterprise-node:4.7
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
      privateCertificate: true
    vault:
      address: http://a39f5128b6763403fbe629cbb6978dc2-1224147318.eu-west-1.elb.amazonaws.com:20001
      certSecretPrefix: secretsv2/data/supplychyn
      serviceAccountName: vault-auth
      role: vault-role
      authPath: cordaentsupplychyn
      retries: 30
      retryInterval: 10
    service:
      p2pPort: 10002
      sshdPort: 2222
      rpc:
        address: "0.0.0.0"
        addressPort: 10003
        admin:
          address: "localhost"
          addressPort: 10770
        standAloneBroker: false
        useSSL: false
        users:
          username: notary
          password: notaryP
    networkServices:
      doormanURL: https://idman.sai29.dev.aws.blockchaincloudpoc-develop.com
      idmanDomain: idman.sai29.dev.aws.blockchaincloudpoc-develop.com
      networkMapURL: https://networkmap.sai29.dev.aws.blockchaincloudpoc-develop.com
      networkMapDomain: networkmap.sai29.dev.aws.blockchaincloudpoc-develop.com
      idmanName: "idman"
      networkmapName: "networkmap"
    dataSourceProperties:
      dataSource:
        password: "notary-1-db-password"
        url: "jdbc:h2:tcp://notary-1db:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
        user: "notary-1-db-user"
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dbUrl: "notary-1db"
      dbPort: 9101
    cordapps:
      getcordapps: true
      jars:
        - url: https://maven.pkg.github.com/hyperledger/bevel/com.supplychain.bcc.cordapp-supply-chain/4.7/cordapp-supply-chain-4.7.jar
        - url: https://maven.pkg.github.com/hyperledger/bevel/com.supplychain.bcc.cordapp-contracts-states/4.7/cordapp-contracts-states-4.7.jar
        
    nodeConf:
      legalName: O=Notary,OU=Notary1,L=London,C=GB
      emailAddress: dev@bevel.com
      notaryPublicIP: notary-1.sai29.dev.aws.blockchaincloudpoc-develop.com
      devMode: false
      notary:
        serviceLegalName: O=Notary Service,OU=Notary1,L=London,C=GB
        validating: True
        type: cenm
      p2p:
        url: notary-1.supplychyn-ent
      ambassador:
        p2pPort: 15040
        external_url_suffix: sai29.dev.aws.blockchaincloudpoc-develop.com
        p2pAddress: notary-1.sai29.dev.aws.blockchaincloudpoc-develop.com:15040
      jarPath: bin
      configPath: etc
      cordaJar:
        memorySize: 1524
        unit: M
      volume:
        baseDir: /opt/corda/base
      pod:
        resources:
          limits: 2056M
          requests: 2056M
      storage:
        name: supplychyn-aws-storageclass
        memory: 512Mi
      replicas: 1
    healthCheckNodePort: 0
    sleepTimeAfterError: 60
    sleepTime: 10
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
