##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

<<<<<<< HEAD:platforms/hyperledger-fabric/configuration/roles/operator/create/ca/server/vars/main.yaml
ca_image_version:
  1.4.8: 1.4.4
  2.2.0: 1.4.8
  2.2.2: 1.4.8
  2.5.3: 1.5.6
=======
apiVersion: v1
appVersion: "2.0"
description: "Hyperledger Fabric: Verifies chaincode."
name: verify_chaincode
version: '0.14.1'
>>>>>>> c7f59cea19fb0eca9ab959f79bbb88760d93d928:platforms/hyperledger-fabric/charts/verify_chaincode/Chart.yaml
