---
name: spell and grammer check
on:
  pull_request:
    paths:
      - ".github/checking.txt"          # provide name of the file or folder

env:
  SPELL_CHECK_DISABLED: false
  GRAMMAR_CHECK_DISABLED: false

jobs:
  check-spelling-and-grammar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Install the dependencies for grammer check and spell check.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling 
        sudo apt-get install hunspell hunspell-en-us aspell aspell-en
        pip install --user --upgrade language_tool_python
      
    - uses: actions/checkout@v2
    - name: Spellcheck
      if: ${{ env.SPELL_CHECK_DISABLED == 'false' }}
      uses: rojopolis/spellcheck-github-actions@0.34.0
      with:
        config_path: .github/.spellcheck.yaml
        source_files: ".github/checking.txt"       # name of the file to check spell 
        task_name: Markdown
    # To check the grammatical mistakes of the given files and folders.
    - name: Run grammar check
      if: ${{ env.GRAMMAR_CHECK_DISABLED == 'false' }}
      run: python .github/grammar_check.py
