---
name: spell check
on:
  push:
    branches:
    - "**"
  pull_request:
    paths:
      - 'docs/**/*.md'
    types: [opened, edited, updated]          

env:
  SPELL_CHECK_DISABLED: false

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Install the dependencies for grammer check and spell check.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling 
        sudo apt-get install hunspell hunspell-en-us aspell aspell-en
        
    - uses: actions/checkout@v2
    - name: Spellcheck
      if: ${{ env.SPELL_CHECK_DISABLED == 'false' }}
      uses: igsekor/pyspelling-any@v0.0.2
      with:
        config_path: .github/.spellcheck.yaml
        source_files: 'docs/source/glossary.md'       # name of the file to check spell 
        task_name: Markdown
