name: Spell Checker
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/spell-checker@v18.04.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          include: |
            **/*.md
            **/*.txt


name: Check Spelling
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request_target:
  issue_comment:
    types: [created]

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
      internal_state_directory: ${{ steps.spelling.outputs.internal_state_directory }}
      docker_container: ${{ steps.spelling.outputs.docker_container }}    