---
name: spell and grammer check
on:
  pull_request:
    paths:
      - "README.md"         # provide name of the file or folder
jobs:
  check-spelling-and-grammar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Install the dependencies for grammer check and spell check.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install pyspelling 
        sudo apt-get install hunspell hunspell-en-us aspell aspell-en
        pip install pylanguagetool
      
    - uses: actions/checkout@v2
    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@0.34.0
      with:
        config_path: .github/.spellcheck.yaml
        source_files: "README.md"       # name of the file to check spell 
        task_name: Markdown
    # To check the grammatical mistakes of the given files and folders.
    - name: Run grammar check
      run: |
        import pylanguagetool

        # Initialize LanguageTool
        tool = pylanguagetool.LanguageTool('en-US')  # You can specify the language you want to check.

        # Read the text from your file
        file_path = 'README.md'  # Update the path accordingly
        with open(file_path, 'r', encoding='utf-8') as file:
            text = file.read()

        # Check for grammar errors
        matches = tool.check(text)

        # Print grammar errors with line numbers
        if matches:
            for match in matches:
                print(f"Grammar error at line {match['offset']} - {match['message']}")
            # Exit with a non-zero code to indicate failure
            exit(1)
        else:
            # No grammar errors found, print a success message
            print("No grammar errors found.")

            # Exit with a zero code to indicate success
            exit(0)
